name: CI devops 2023

on:
  push:
    branches:
      - main
      - develop
  pull_request:
jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Build and test with maven
        working-directory: simple-api-student
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=test-marmar_devops -Dsonar.organization=test-marmar -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  -f ./pom.xml

  build-and-push-docker-images:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api-student # Relative path to the source code with Dockerfile
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push database Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./database # Relative path to the source code with Dockerfile
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push httpd Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend  # Relative path to the source code with Dockerfile
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}
